import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {

	// Register the command defined in package.json
	let disposable = vscode.commands.registerCommand('json-to-dart.convert', async () => {

		const editor = vscode.window.activeTextEditor;
		if (!editor) {
			vscode.window.showErrorMessage("No active editor found!");
			return;
		}

		// 1. Get the selected text
		const selection = editor.selection;
		const text = editor.document.getText(selection);

		if (!text) {
			vscode.window.showErrorMessage("Please select some JSON text first.");
			return;
		}

		try {
			// 2. Parse JSON and Generate Dart Code
			const jsonObject = JSON.parse(text);
			const className = await vscode.window.showInputBox({
				prompt: "Enter the Dart class name",
				value: "AutoGenerated"
			});

			if (!className) { return; } // User cancelled

			const dartCode = generateDartClass(className, jsonObject);

			// 3. Replace selected text with generated Dart code
			editor.edit(editBuilder => {
				editBuilder.replace(selection, dartCode);
			});

		} catch (error) {
			vscode.window.showErrorMessage("Invalid JSON: " + error);
		}
	});

	context.subscriptions.push(disposable);
}

// --- Helper Function: The "Engine" of your extension ---
function generateDartClass(className: string, json: any): string {
	let properties = "";
	let constructorParams = "";
	let fromJsonLogic = "";
	let toJsonLogic = "";

	// Loop through JSON keys to build class fields
	for (const key in json) {
		if (json.hasOwnProperty(key)) {
			const value = json[key];
			const type = getDartType(value);

			// Basic property definition
			properties += `  final ${type} ${key};\n`;

			// Constructor param
			constructorParams += `    required this.${key},\n`;

			// fromJson logic
			fromJsonLogic += `      ${key}: json['${key}'],\n`;

			// toJson logic
			toJsonLogic += `      '${key}': ${key},\n`;
		}
	}

	return `
class ${className} {
${properties}
  ${className}({
${constructorParams}  });

  factory ${className}.fromJson(Map<String, dynamic> json) {
    return ${className}(
${fromJsonLogic}    );
  }

  Map<String, dynamic> toJson() {
    return {
${toJsonLogic}    };
  }
}
`;
}

function getDartType(value: any): string {
	if (typeof value === 'string') { return 'String'; }
	if (typeof value === 'number') { return Number.isInteger(value) ? 'int' : 'double'; }
	if (typeof value === 'boolean') { return 'bool'; }
	if (Array.isArray(value)) { return 'List<dynamic>'; } // Simplified for this example
	return 'Map<String, dynamic>'; // Fallback for objects
}

export function deactivate() { }
